выполнила 1ю страницу
htmlacademy-htmlcss/1806013-technomart-31 pull request #3
Opened 2021-05-23 15:31 UTC by Kungfu-Chsia

2021-05-24 22:05 UTC, avylando requested changes
В целом структура странички хорошая, есть обычные проблемы связанные с семантикой элементов, перепутанные кнопки и ссылки и т.д. - это нормально. Кое-где у тебя невалидная верстка из-за забытых или незакрытых тегов, рекомендую использовать какой-нибудь редактор типа VS Code c подсветкой синтаксиса и автозакрытием тегов, очень помогает избегать таких ошибок

2021-05-24 22:05 UTC, avylando commented on index.html
> +        <a href="mail:mail@htmlacademy.ru">mail@htmlacademy.ru</a>
Правильнее так - href="mail**to**:mail@htmlacademy.ru"

2021-05-25 03:37 UTC, Kungfu-Chsia commented on index.html
> +      <button type="button">25 500</button></div>
невалидная разметка это лишний тег?
где именно тут текст?

2021-05-25 03:42 UTC, Kungfu-Chsia commented on index.html
> +  <li><a href="#">ЖелДорЭкспедиция</a></li>
точно не ссылки? как проверить, что не ссылки?
может, конторы заплатили за рекламу , и размещены ссылки на сайт?

2021-05-25 03:43 UTC, Kungfu-Chsia commented on index.html
> +    <p>г. Санкт-Петербург, наб. Реки Карповки, 5 лит П +7 800 555-86-28</p>
телефоны везде желательно делать ссылкой?

2021-05-25 03:44 UTC, Kungfu-Chsia commented on index.html
> +        <a href="mail:mail@htmlacademy.ru">mail@htmlacademy.ru</a>
скопировала из Барбершопа))

2021-05-25 11:28 UTC, avylando commented on index.html
> +    <p>г. Санкт-Петербург, наб. Реки Карповки, 5 лит П +7 800 555-86-28</p>
Желательно да, это удобно и доступно для пользователей

2021-05-25 11:30 UTC, avylando commented on index.html
> +      <button type="button">25 500</button></div>
Да, лишний тег, проверить можно на валидаторе https://validator.w3.org/

Текст это контент внутри тега, в данном случае цена

2021-05-28 23:22 UTC, avylando reviewed
Привет! Еще остались незакрытые замечания по первой страничке, по второй тоже написал
Чтобы не тормозить процесс принимаю так, поправь пожалуйста все в соедующем пуллреквесте

2021-05-28 23:22 UTC, avylando commented on index.html
> +    </li>
У тебя тут li внутри li, поправь

2021-05-28 23:22 UTC, avylando commented on index.html
> +      <button type="button">25 500 Р.</button>
Это не button, а обычный блок

2021-05-28 23:22 UTC, avylando commented on index.html
> +    <li class="carousel__item1"> <p>Оформить Кредит...</p></li>
Тут слайды нужно разметить полностью, с заголовками и картинками + полный текст

2021-05-28 23:22 UTC, avylando commented on index.html
> +  <li><P>Деловые линии</p></li>
Р заглавная - поправь

2021-05-28 23:22 UTC, avylando commented on index.html
> +<button type="button">Подробнее о компании</button>
Тут опять ссылка должна быть) Если предполагается переход на другую страницу, переход к какой-то новой информации, то это практически на 100% ссылка

2021-05-28 23:22 UTC, avylando commented on catalog.html
> +              <H2>Перфораторы</H2>
Заглавные теги, делай строчными

2021-05-28 23:22 UTC, avylando commented on catalog.html
> +                <form method="get" action="https://#.ru">
action странный конечно)

2021-05-28 23:22 UTC, avylando commented on index.html
> +    <a href="#">Открыть каталог</a>
Тут и везде где нужно сделай пожалуйста ссылку на страницу каталога

2021-05-28 23:22 UTC, avylando commented on catalog.html
> +              <p>ПЕРФОРАТОРЫ</p>
Не нужно дублировать заголовки, тут p убери и оставь только заголовок

2021-05-28 23:22 UTC, avylando commented on catalog.html
> +              <p>Сортировка</p>
Здесь тоже, достаточно только заголовка

2021-05-28 23:22 UTC, avylando commented on catalog.html
> +              <button type="button">25 500 Р.</button>
Напишу еще раз - это не кнопки)

2021-05-28 23:22 UTC, avylando commented on catalog.html
> +                  <a>1</a>
Добавь здесь тоже href

2021-05-28 23:22 UTC, avylando commented on catalog.html
> +            <p>г. Санкт-Петербург, наб. Реки Карповки, 5 лит П </p>
Это кстати можно разметить тегом adress - не критично, но просто как совет

2021-05-28 23:23 UTC, merged